const dictionary = {
  "arte": { synonyms:["bellas artes","expresión artística"], broader:["cultura"], narrower:["pintura","escultura"] },
  "danza": { synonyms:["baile","coreografía"], broader:["arte"], narrower:["ballet","danza contemporánea"] },
  "música": { synonyms:["sonido","composición musical"], broader:["arte"], narrower:["música clásica","música contemporánea"] },
  "pintura": { synonyms:["óleo","acuarela","arte pictórico"], broader:["arte"], narrower:["pintura moderna","pintura clásica"] },
  "escultura": { synonyms:["talla","modelado","estatua"], broader:["arte"], narrower:["escultura clásica","escultura contemporánea"] },
  "teatro": { synonyms:["drama","actuación","representación escénica"], broader:["arte"], narrower:["teatro clásico","teatro moderno"] },
  "cine": { synonyms:["film","película","industria cinematográfica"], broader:["arte"], narrower:["cine clásico","cine contemporáneo"] },
  "fotografía": { synonyms:["imagen","captura","retrato"], broader:["arte visual"], narrower:["fotografía artística","fotografía documental"] },
  "arquitectura": { synonyms:["construcción","diseño","edificación"], broader:["arte"], narrower:["arquitectura clásica","arquitectura moderna"] },
  "escenografía": { synonyms:["ambientación","decorado","puesta en escena"], broader:["teatro"], narrower:["escenografía teatral","escenografía cinematográfica"] },
  "performance": { synonyms:["actuación","representación","show"], broader:["arte contemporáneo"], narrower:["performance artístico","performance musical"] },
  "identidad": { synonyms:["personalidad","carácter","autoconcepto"], broader:["psicología"], narrower:["identidad de género","identidad cultural"] },
  "conflicto": { synonyms:["disputa","tensión","desacuerdo"], broader:["sociedad"], narrower:["conflicto social","conflicto político"] },
  "memoria": { synonyms:["recuerdo","historia personal","reminiscencia"], broader:["historia"], narrower:["memoria colectiva","memoria cultural"] },
  "tradición": { synonyms:["costumbre","herencia","ritual"], broader:["cultura"], narrower:["tradición oral","tradición artística"] },
  "diversidad": { synonyms:["variedad","heterogeneidad","pluralidad"], broader:["sociedad"], narrower:["diversidad cultural","diversidad lingüística"] },
  "belleza": { synonyms:["estética","hermosura","atractivo"], broader:["arte","percepción"], narrower:["belleza natural","belleza artística"] },
  "estética": { synonyms:["sensibilidad artística","percepción","armonía"], broader:["filosofía"], narrower:["estética del arte","estética corporal"] },
  "diseño": { synonyms:["creación","proyecto","planificación"], broader:["arte"], narrower:["diseño gráfico","diseño industrial"] },
  "moda": { synonyms:["tendencia","estilo","vestimenta"], broader:["cultura"], narrower:["alta costura","moda urbana"] },
  "ética": { synonyms:["moral","principios","valores"], broader:["filosofía"], narrower:["ética profesional","ética social"] },
  "moral": { synonyms:["principios","valores","conducta"], broader:["ética"], narrower:["moral personal","moral colectiva"] },
  "existencia": { synonyms:["vida","ser","realidad"], broader:["filosofía"], narrower:["existencia humana","existencia social"] },
  "conocimiento": { synonyms:["saber","ciencia","aprendizaje"], broader:["filosofía"], narrower:["conocimiento práctico","conocimiento teórico"] },
  "verdad": { synonyms:["realidad","hecho","certeza"], broader:["filosofía"], narrower:["verdad objetiva","verdad subjetiva"] },
  "vida": { synonyms:["existencia","ser","vivir"], broader:["filosofía"], narrower:["vida personal","vida social"] },
  "comunidad": { synonyms:["colectivo","grupo","sociedad"], broader:["sociedad"], narrower:["comunidad urbana","comunidad rural"] },
  "justicia": { synonyms:["equidad","derecho","legalidad"], broader:["moral"], narrower:["justicia social","justicia legal"] },
  "libertad": { synonyms:["autonomía","derechos","voluntad"], broader:["sociedad"], narrower:["libertad personal","libertad social"] },
  "responsabilidad": { synonyms:["obligación","compromiso","deber"], broader:["moral"], narrower:["responsabilidad personal","responsabilidad social"] },
  "tecnología": { synonyms:["innovación técnica","herramientas","aplicaciones"], broader:["ciencias aplicadas"], narrower:["tecnología digital","tecnología educativa","tecnología de la información"] },
  "informática": { synonyms:["computación","procesamiento de datos","software"], broader:["tecnología"], narrower:["programación","sistemas operativos","redes informáticas"] },
  "software": { synonyms:["programa","aplicación","sistema"], broader:["informática"], narrower:["software educativo","software de diseño","software empresarial"] },
  "hardware": { synonyms:["equipo","dispositivo","componentes"], broader:["informática"], narrower:["hardware de computadora","hardware de telecomunicaciones"] },
  "inteligencia artificial": { synonyms:["IA","aprendizaje automático","machine learning"], broader:["tecnología"], narrower:["IA aplicada","IA creativa","IA ética"] },
  "robotica": { synonyms:["robots","automatización","máquinas inteligentes"], broader:["tecnología"], narrower:["robótica industrial","robótica educativa","robótica de servicios"] },
  "big data": { synonyms:["datos masivos","análisis de datos","información"], broader:["informática"], narrower:["análisis predictivo","visualización de datos","minería de datos"] },
  "innovación": { synonyms:["novedad","mejora","creación"], broader:["desarrollo"], narrower:["innovación tecnológica","innovación social","innovación educativa"] },
  "emprendimiento": { synonyms:["startup","negocio emergente","empresa nueva"], broader:["economía"], narrower:["emprendimiento tecnológico","emprendimiento cultural"] },
  "creatividad": { synonyms:["imaginación","invención","originalidad"], broader:["habilidades humanas"], narrower:["creatividad artística","creatividad científica","creatividad digital"] },
  "diseño de producto": { synonyms:["desarrollo de producto","prototipo","planificación de diseño"], broader:["innovación"], narrower:["diseño industrial","diseño gráfico","diseño interactivo"] },
  "prototipo": { synonyms:["modelo","maqueta","prueba"], broader:["diseño de producto"], narrower:["prototipo funcional","prototipo digital","prototipo experimental"] },
  "metodología": { synonyms:["procedimiento","sistema","técnica"], broader:["investigación"], narrower:["metodología científica","metodología de diseño","metodología de innovación"] },
  "investigación": { synonyms:["estudio","análisis","exploración"], broader:["ciencia"], narrower:["investigación científica","investigación aplicada","investigación educativa"] },
  "experimento": { synonyms:["prueba","ensayo","evaluación"], broader:["investigación"], narrower:["experimento controlado","experimento de laboratorio","experimento de campo"] },
  "análisis de datos": { synonyms:["procesamiento de información","estadística","minería de datos"], broader:["investigación"], narrower:["análisis cuantitativo","análisis cualitativo","análisis predictivo"] },
  "innovación abierta": { synonyms:["colaboración","co-creación","participación"], broader:["innovación"], narrower:["innovación tecnológica abierta","innovación social abierta"] },
  "laboratorio": { synonyms:["taller","centro de investigación","instituto"], broader:["investigación"], narrower:["laboratorio físico","laboratorio virtual","laboratorio de innovación"] },
  "publicación científica": { synonyms:["artículo","paper","documento académico"], broader:["investigación"], narrower:["revista científica","congreso","libro académico"] }
};
